### ISSUE TITLE
Not working on SF314-42 (v.1.10)

### ISSUE THREAD

**Issue by Spitfireap** [lbschenkel/acer-sf314_43-acpi-patch#1]
I was hoping this could work on my acer since I have the same issue, and since the option in the bios for S3 state is hidden since v1.03, do you think you could add compatibility for this laptop ? 
Thanks !
[acpidump.log](https://github.com/lbschenkel/acer-sf314_43-acpi-patch/files/8239263/acpidump.log)

**Comment by Spitfireap** [comment]
I've applied the manual method, and despite following the guide, it seems _acpidump_ does not change after reboot...

**Comment by lbschenkel** [comment]
I don't know what you mean by:
> *acpidump* does not change after reboot

**Comment by Spitfireap** [comment]
If I unpack it to the dsdt.dsl after reboot, my changes aren't showed. I don't know anything about ACPI so maybe it's expected ?

**Comment by lbschenkel** [comment]
Follow the manual instructions to the letter. Were you able to complete all steps without errors, including applying the patch in step 4? I don't expect the patch to apply in different models with different BIOSes.

**Comment by Spitfireap** [comment]
I wasn't able to apply it automatically, but I modified the file manually to reflect the same change you did.

**Comment by lbschenkel** [comment]
Right. Were you then able to perform steps 5 and 6 and configure the bootloader accordingly?
If it worked, you should see this after a boot:
```sh
# dmesg | grep ACPI | grep supports
kernel: ACPI: PM: (supports S0 S3 S4 S5)

# cat /sys/power/mem_sleep                                                            ✔  
s2idle [deep]
```

**Comment by Spitfireap** [comment]
Okay sorry, override didn't apply because I misconfigured grub. It's working great now, thanks !!

**Comment by peterhoeg** [comment]
Would it be an idea to start adding support for other acer machines in here?

**Comment by lbschenkel** [comment]
I would rather not, to be honest. I only want to publish things that I use and/or test myself. I don't think it is appropriate for me to host patches for other machines. Somebody else should do that for the machines they have and if somebody really feels like it, aggregate all patches in some sort of umbrella project.

By keeping the repo hyper-focused we can maximize the chances that I can keep maintaining it in my limited free time.

**Comment by lbschenkel** [comment]
I would rather not, to be honest. I only want to publish things that I use and/or test myself. I don't think it is appropriate for me to host patches for other machines. Somebody else should do that for the machines they have and if somebody really feels like it, aggregate all patches in some sort of umbrella project.

By keeping the repo hyper-focused we can maximize the chances that I can keep maintaining it in my limited free time.

**Comment by peterhoeg** [comment]
Fair enough. Besides, I have the -43 so I’m happy! ;-)
