### ISSUE TITLE
not working, even though it should

### ISSUE THREAD

**Issue by piramiday** [lbschenkel/acer-sf314_43-acpi-patch#2]
hey there, I found myself in the same situation as yours, hoping that your repo could save the day: unfortunately, I cannot get it to work.

I have an Acer Swift 3 SF314-43 with BIOS v1.04, and I recently installed Linux Mint 20.3 (based on Ubuntu 20.04 LTS), which shipped with kernel 5.04 although I later installed kernel 5.15 through the PPA `canonical-kernel-team/proposed`.

I did the following:
- `sudo apt install acpica-tools`
- `git clone https://github.com/lbschenkel/acer-sf314_43-acpi-patch.git`
- `cd acer-sf314_43-acpi-patch`

then, `make`:

<details><summary>Output from `make`</summary><p>

```

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20190509
Copyright (c) 2000 - 2019 Intel Corporation

File appears to be binary: found 10509 non-ASCII characters, disassembling
Binary file appears to be a valid ACPI table, disassembling
Input file acpi/dsdt.dat, Length 0x7EB6 (32438) bytes
ACPI: DSDT 0x0000000000000000 007EB6 (v01 ACRSYS ACRPRDCT 00000002 1025 00040000)
External object resolution file    acpi/wsmt.dat
Input file acpi/wsmt.dat, Length 0x28 (40) bytes
    acpi/wsmt.dat: Table [WSMT] is not an AML table - ignoring
External object resolution file    acpi/vfct.dat
Input file acpi/vfct.dat, Length 0xD884 (55428) bytes
    acpi/vfct.dat: Table [VFCT] is not an AML table - ignoring
External object resolution file    acpi/uefi.dat
Input file acpi/uefi.dat, Length 0x236 (566) bytes
    acpi/uefi.dat: Table [UEFI] is not an AML table - ignoring
External object resolution file   acpi/ssdt9.dat
Input file acpi/ssdt9.dat, Length 0xD53 (3411) bytes
ACPI: SSDT 0x0000000000000000 000D53 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt8.dat
Input file acpi/ssdt8.dat, Length 0x28D (653) bytes
ACPI: SSDT 0x0000000000000000 00028D (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt7.dat
Input file acpi/ssdt7.dat, Length 0x139 (313) bytes
ACPI: SSDT 0x0000000000000000 000139 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt6.dat
Input file acpi/ssdt6.dat, Length 0x3E88 (16008) bytes
ACPI: SSDT 0x0000000000000000 003E88 (v02 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt5.dat
Input file acpi/ssdt5.dat, Length 0xF8 (248) bytes
ACPI: SSDT 0x0000000000000000 0000F8 (v01 ACRSYS ACRPRDCT 00001000 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt4.dat
Input file acpi/ssdt4.dat, Length 0x6BD7 (27607) bytes
ACPI: SSDT 0x0000000000000000 006BD7 (v01 ACRSYS ACRPRDCT 00001000 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt3.dat
Input file acpi/ssdt3.dat, Length 0x80 (128) bytes
ACPI: SSDT 0x0000000000000000 000080 (v01 ACRSYS ACRPRDCT 00000002 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt2.dat
Input file acpi/ssdt2.dat, Length 0x3A24 (14884) bytes
ACPI: SSDT 0x0000000000000000 003A24 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt17.dat
Input file acpi/ssdt17.dat, Length 0x517 (1303) bytes
ACPI: SSDT 0x0000000000000000 000517 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt16.dat
Input file acpi/ssdt16.dat, Length 0x7D (125) bytes
ACPI: SSDT 0x0000000000000000 00007D (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt15.dat
Input file acpi/ssdt15.dat, Length 0x2CD (717) bytes
ACPI: SSDT 0x0000000000000000 0002CD (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt14.dat
Input file acpi/ssdt14.dat, Length 0x57D (1405) bytes
ACPI: SSDT 0x0000000000000000 00057D (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt13.dat
Input file acpi/ssdt13.dat, Length 0x20A (522) bytes
ACPI: SSDT 0x0000000000000000 00020A (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt12.dat
Input file acpi/ssdt12.dat, Length 0x42 (66) bytes
ACPI: SSDT 0x0000000000000000 000042 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt11.dat
Input file acpi/ssdt11.dat, Length 0x34A4 (13476) bytes
ACPI: SSDT 0x0000000000000000 0034A4 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file  acpi/ssdt10.dat
Input file acpi/ssdt10.dat, Length 0x10A5 (4261) bytes
ACPI: SSDT 0x0000000000000000 0010A5 (v01 ACRSYS ACRPRDCT 00000001 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file   acpi/ssdt1.dat
Input file acpi/ssdt1.dat, Length 0x7229 (29225) bytes
ACPI: SSDT 0x0000000000000000 007229 (v02 ACRSYS ACRPRDCT 00000002 1025 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file    acpi/msdm.dat
Input file acpi/msdm.dat, Length 0x55 (85) bytes
    acpi/msdm.dat: Table [MSDM] is not an AML table - ignoring
External object resolution file    acpi/mcfg.dat
Input file acpi/mcfg.dat, Length 0x3C (60) bytes
    acpi/mcfg.dat: Table [MCFG] is not an AML table - ignoring
External object resolution file    acpi/ivrs.dat
Input file acpi/ivrs.dat, Length 0x1A4 (420) bytes
    acpi/ivrs.dat: Table [IVRS] is not an AML table - ignoring
External object resolution file    acpi/hpet.dat
Input file acpi/hpet.dat, Length 0x38 (56) bytes
    acpi/hpet.dat: Table [HPET] is not an AML table - ignoring
External object resolution file    acpi/fpdt.dat
Input file acpi/fpdt.dat, Length 0x44 (68) bytes
    acpi/fpdt.dat: Table [FPDT] is not an AML table - ignoring
External object resolution file    acpi/facs.dat
Input file acpi/facs.dat, Length 0x40 (64) bytes
ACPI Warning: Table header for [FACS] has invalid ASCII character(s) (20190509/acfileio-515)
    acpi/facs.dat: Table [FACS] is not an AML table - ignoring
External object resolution file    acpi/facp.dat
Input file acpi/facp.dat, Length 0x10C (268) bytes
    acpi/facp.dat: Table [FACP] is not an AML table - ignoring
External object resolution file    acpi/crat.dat
Input file acpi/crat.dat, Length 0xBA8 (2984) bytes
    acpi/crat.dat: Table [CRAT] is not an AML table - ignoring
External object resolution file    acpi/cdit.dat
Input file acpi/cdit.dat, Length 0x29 (41) bytes
    acpi/cdit.dat: Table [CDIT] is not an AML table - ignoring
External object resolution file    acpi/boot.dat
Input file acpi/boot.dat, Length 0x28 (40) bytes
    acpi/boot.dat: Table [BOOT] is not an AML table - ignoring
External object resolution file    acpi/bgrt.dat
Input file acpi/bgrt.dat, Length 0x38 (56) bytes
    acpi/bgrt.dat: Table [BGRT] is not an AML table - ignoring
External object resolution file    acpi/asf!.dat
Input file acpi/asf!.dat, Length 0xA5 (165) bytes
    acpi/asf!.dat: Table [ASF!] is not an AML table - ignoring
External object resolution file    acpi/apic.dat
Input file acpi/apic.dat, Length 0x138 (312) bytes
    acpi/apic.dat: Table [APIC] is not an AML table - ignoring
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed

Found 23 external control methods, reparsing with new information
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed
Disassembly completed
ASL Output:    acpi/dsdt.dsl - 275192 bytes

 iASL Warning: There were 23 external control methods found during
 disassembly, but only 22 were resolved (1 unresolved). Additional
 ACPI tables may be required to properly disassemble the code. This
 resulting disassembler output file may not compile because the
 disassembler did not know how many arguments to assign to the
 unresolved methods. Note: SSDTs can be dynamically loaded at
 runtime and may or may not be available via the host OS.

 In addition, the -fe option can be used to specify a file containing
 control method external declarations with the associated method
 argument counts. Each line of the file must be of the form:
     External (<method pathname>, MethodObj, <argument count>)
 Invocation:
     iasl -fe refs.txt -d dsdt.aml

patching file acpi/dsdt-patched.dsl (read from acpi/dsdt.dsl)
Hunk #1 succeeded at 18 with fuzz 2.
Hunk #2 succeeded at 829 (offset 20 lines).
'acpi/dsdt.dsl' -> 'acpi/dsdt-patched.dsl'

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20190509
Copyright (c) 2000 - 2019 Intel Corporation

ACPI Warning: NsLookup: Type mismatch on ACMX (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on PMRI (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on PM2I (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on PM0I (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on PIDX (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on ECMI (RegionField), searching for (Region) (20190509/nsaccess-732)
ACPI Warning: NsLookup: Type mismatch on FPII (RegionField), searching for (Region) (20190509/nsaccess-732)
ASL Input:     acpi/dsdt-patched.dsl -  275192 bytes   3333 keywords   8734 source lines
AML Output:    acpi/dsdt-patched.aml -   32972 bytes   2352 opcodes     981 named objects

Compilation successful. 0 Errors, 23 Warnings, 38 Remarks, 69 Optimizations
66 blocchi

SUCCESS!
Now you have to instruct your boot loader to:
1. load an (additional) initrd:    /boot/acpi-override.img
2. add to the kernel command line: mem_sleep_default=deep

GRUB:
 1. Add to /etc/default/grub:
    GRUB_EARLY_INITRD_LINUX_CUSTOM="acpi-override.img"
    GRUB_CMDLINE_LINUX_DEFAULT="... mem_sleep_default=deep"
 2. Run update-grub
systemd-boot:
 Add to /boot/loader/entries/*.conf:
  initrd  /acpi-override.img
  options ... mem_sleep_default=deep
rEFInd:
 1. Add to /boot/refind-linux.conf: "Boot with default options" "initrd=acpi-override.img ..."
 2. Add to manual stanzas:          options "initrd=acpi-override.img ... mem_sleep_default=deep"
```

</details>

and finally I modified my `grub` configuration, with result:
```
user@host:~$ grep -e GRUB_EARLY_INITRD_LINUX_CUSTOM -e GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub

GRUB_EARLY_INITRD_LINUX_CUSTOM="acpi-override.img"
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mem_sleep_default=deep"
```

still, after rebooting and making sure that the grub configuration has been applied:
```
user@host:~ cat /sys/power/mem_sleep 

[s2idle]
```

any suggestion? thanks!

**Comment by lbschenkel** [comment]
1. Check if `acpi-override.img` can be found in `/boot`
2. Check if `cat /proc/cmdline` includes `mem_sleep_default=deep`

Maybe you didn't run `update-grub` after changing the config files? Make sure to run it, and then reboot.

**Comment by piramiday** [comment]
sorry, I posted this issue a bit too hastily, but yeah -- I did check all of the following.

1. `acpi-override.img` is present.
2. `cat /proc/cmdline` does include `mem_sleep_default=deep`
3. I did run `update-grub`.

if it's of any help, I did try your procedure on the kernel 5.04 as well, before realizing that you had a 5.15 kernel.
with both kernels nothing happens, unfortunately.
any further suggestion?

**Comment by lbschenkel** [comment]
I find this very strange. I believe that the kernel version should not be too important, the ACPI overriding functionality is quite old.

Looking at the output of `patch` in your system this caught my eye:
```
patching file acpi/dsdt-patched.dsl (read from acpi/dsdt.dsl)
Hunk #1 succeeded at 18 with fuzz 2.
Hunk #2 succeeded at 829 (offset 20 lines).
'acpi/dsdt.dsl' -> 'acpi/dsdt-patched.dsl'
```
If your system and BIOS are exactly the same as mine, then the patch should apply without any fuzzing or offset. The fact that it did happen for you see to indicate that you either:
(1) have a slightly different BIOS somehow
(2) `acpica` is different enough that it produced a slightly different decompile

If you do have a slightly different BIOS, and the `DefinitionBlock` in yours has version `0x00000003` or higher, then it could explain why the override did not work: for it to work the new patched tables must have a newer version than the version in the BIOS, otherwise Linux ignores them.

Can you do the following?
1. Run `acpidump -b` to dump all ACPI tables to `*.dat` files
2. Run `iasl -e *.dat -d dsdt.dat` to decompile the DSDT table to `dsdt.dsl`

And then look at `dsdt.dsl` and paste here the `DefinitionBlock` line in the beginning on the file. What this patch expects is:
```
DefinitionBlock ("", "DSDT", 1, "ACRSYS", "ACRPRDCT", 0x00000002)
```

**Comment by piramiday** [comment]
thanks for your prompt reply. here it is:
```
$ sudo acpidump -b
$ sudo iasl -e *.dat -d dsdt.dat
[...]
$ grep Definition dsdt.dsl
DefinitionBlock ("", "DSDT", 1, "ACRSYS", "ACRPRDCT", 0x00000002)
```
which corresponds to yours, if my eyes do not betray me.

could it be that the 20-line offset is just header comments?
```
$ head -n20 dsdt.dsl
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20190509 (64-bit version)
 * Copyright (c) 2000 - 2019 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of dsdt.dat, Mon Apr 11 16:39:08 2022
 *
 * Original Table Header:
 *     Signature        "DSDT"
 *     Length           0x00007EB6 (32438)
 *     Revision         0x01 **** 32-bit table (V1), no 64-bit math support
 *     Checksum         0x05
 *     OEM ID           "ACRSYS"
 *     OEM Table ID     "ACRPRDCT"
 *     OEM Revision     0x00000002 (2)
 *     Compiler ID      "1025"
 *     Compiler Version 0x00040000 (262144)
 */
```

also, my APT-installed `acpica-tools` version is as follows:
```
$ apt list --installed | grep acpica

acpica-tools/focal,now 20190509-1 amd64 [installed]
```

**Comment by lbschenkel** [comment]
> which corresponds to yours, if my eyes do not betray me.

Yes, nothing seems to be wrong there.

> could it be that the 20-line offset is just header comments?

The patch file I generated was against the same file with comments as well, so ideally there should not be an offset.

I'm out of ideas. Are you willing to attach the original `dsdt.dsl` and the version with the patch applied? The only other thing I can do is to diff against mine. If those are identical, then I can't explain why it doesn't work for you.

**Comment by piramiday** [comment]
of course! here are the two files:
- [dsdt.dsl.orig](https://github.com/lbschenkel/acer-sf314_43-acpi-patch/files/8465217/dsdt.dsl.orig.txt)
- [dsdt.dsl](https://github.com/lbschenkel/acer-sf314_43-acpi-patch/files/8465225/dsdt.dsl.txt)

and here is the `diff`erence:

```
$ diff dsdt.dsl.orig dsdt.dsl
21c21
< DefinitionBlock ("", "DSDT", 1, "ACRSYS", "ACRPRDCT", 0x00000002)
---
> DefinitionBlock ("", "DSDT", 1, "ACRSYS", "ACRPRDCT", 0x00000003)
832c832
<     If ((CNSB == Zero))
---
>     Name (_S3, Package (0x04)  // _S3_: S3 System State
834,845c834,838
<         If ((DAS3 == One))
<         {
<             Name (_S3, Package (0x04)  // _S3_: S3 System State
<             {
<                 0x03, 
<                 0x03, 
<                 Zero, 
<                 Zero
<             })
<         }
<     }
< 
---
>         0x03, 
>         0x03, 
>         Zero, 
>         Zero
>     })
```

do you have an example of your output from the patching?
also, which version of the `acpi-tools` package do you have? I could try and downgrade...

**Comment by piramiday** [comment]
well, I managed to get it to work by following the manual approach! I cannot believe I did not try that sooner. (*)
based on the fact that my `acpi-override.img` is now different than what was previously under `/boot`, I guess there is some workflow issue in your makefile, rather than in the DSDT patch.

I am more than willing to help you iron out the details, if you are interested.
(*): as a suggestion, you could try and explicitly print out the necessary commands, because reconstructing those from the makefile is definitely error-prone... I could now do this thanks to this hour-long debugging process, not earlier.
maybe my `acpi-ovveride.img` was simply a recompiled, unpatched, version of the original DSDT file?

**Comment by lbschenkel** [comment]
It looks like the difference is due to `acpica`. This is the diff between your tables and mine (pre-patching):
```diff
--- acpi/dsdt.dsl	2022-04-11 17:10:16.665255393 +0200
+++ dsdt.dsl.orig.txt	2022-04-11 17:11:36.938712314 +0200
@@ -1,17 +1,17 @@
 /*
  * Intel ACPI Component Architecture
- * AML/ASL+ Disassembler version 20211217 (64-bit version)
- * Copyright (c) 2000 - 2021 Intel Corporation
+ * AML/ASL+ Disassembler version 20190509 (64-bit version)
+ * Copyright (c) 2000 - 2019 Intel Corporation
  * 
  * Disassembling to symbolic ASL+ operators
  *
- * Disassembly of acpi/dsdt.dat, Mon Apr 11 17:10:16 2022
+ * Disassembly of dsdt.dat, Mon Apr 11 16:52:33 2022
  *
  * Original Table Header:
  *     Signature        "DSDT"
  *     Length           0x00007EB6 (32438)
  *     Revision         0x01 **** 32-bit table (V1), no 64-bit math support
- *     Checksum         0x17
+ *     Checksum         0x05
  *     OEM ID           "ACRSYS"
  *     OEM Table ID     "ACRPRDCT"
  *     OEM Revision     0x00000002 (2)
@@ -20,6 +20,26 @@
  */
 DefinitionBlock ("", "DSDT", 1, "ACRSYS", "ACRPRDCT", 0x00000002)
 {
+    /*
+     * iASL Warning: There were 23 external control methods found during
+     * disassembly, but only 22 were resolved (1 unresolved). Additional
+     * ACPI tables may be required to properly disassemble the code. This
+     * resulting disassembler output file may not compile because the
+     * disassembler did not know how many arguments to assign to the
+     * unresolved methods. Note: SSDTs can be dynamically loaded at
+     * runtime and may or may not be available via the host OS.
+     *
+     * In addition, the -fe option can be used to specify a file containing
+     * control method external declarations with the associated method
+     * argument counts. Each line of the file must be of the form:
+     *     External (<method pathname>, MethodObj, <argument count>)
+     * Invocation:
+     *     iasl -fe refs.txt -d dsdt.aml
+     *
+     * The following methods were unresolved and many not compile properly
+     * because the disassembler had to guess at the number of arguments
+     * required for each:
+     */
     External (_SB_.ALIB, MethodObj)    // 2 Arguments
     External (_SB_.APTS, MethodObj)    // 1 Arguments
     External (_SB_.AWAK, MethodObj)    // 1 Arguments
@@ -39,11 +59,11 @@
     External (_SB_.PLTF.C009._PPC, MethodObj)    // 0 Arguments
     External (_SB_.PLTF.C00A._PPC, MethodObj)    // 0 Arguments
     External (_SB_.PLTF.C00B._PPC, MethodObj)    // 0 Arguments
-    External (_SB_.PLTF.C00C._PPC, MethodObj)    // 0 Arguments
-    External (_SB_.PLTF.C00D._PPC, MethodObj)    // 0 Arguments
-    External (_SB_.PLTF.C00E._PPC, MethodObj)    // 0 Arguments
-    External (_SB_.PLTF.C00F._PPC, MethodObj)    // 0 Arguments
-    External (_SB_.TPM2.PTS_, MethodObj)    // 1 Arguments
+    External (_SB_.PLTF.C00C._PPC, UnknownObj)
+    External (_SB_.PLTF.C00D._PPC, UnknownObj)
+    External (_SB_.PLTF.C00E._PPC, UnknownObj)
+    External (_SB_.PLTF.C00F._PPC, UnknownObj)
+    External (_SB_.TPM2.PTS_, MethodObj)    // Warning: Unknown method, guessing 1 arguments
     External (AFN4, MethodObj)    // 1 Arguments
     External (M017, MethodObj)    // 6 Arguments
     External (M019, MethodObj)    // 4 Arguments
@@ -575,7 +595,7 @@
 
     Name (BUFN, Zero)
     Name (MBUF, Buffer (0x1000){})
-    OperationRegion (MDBG, SystemMemory, 0xCCEB3018, 0x00001004)
+    OperationRegion (MDBG, SystemMemory, 0xCCED4018, 0x00001004)
     Field (MDBG, AnyAcc, Lock, Preserve)
     {
         MDG0,   32768
@@ -4337,7 +4357,7 @@
 
                     Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
                     {
-                        If ((Arg0 == ToUUID ("6f8398c2-7ca4-11e4-ad36-631042b5008f") /* Unknown UUID */))
+                        If ((Arg0 == ToUUID ("6f8398c2-7ca4-11e4-ad36-631042b5008f")))
                         {
                             Switch (ToInteger (Arg2))
                             {
@@ -4492,7 +4512,7 @@
 
                     Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
                     {
-                        ToUUID ("5025030f-842f-4ab4-a561-99a5189762d0") /* Unknown UUID */, 
+                        ToUUID ("5025030f-842f-4ab4-a561-99a5189762d0"), 
                         Package (0x01)
                         {
                             Package (0x02)
@@ -4705,7 +4725,7 @@
 
                     Name (_DSD, Package (0x02)  // _DSD: Device-Specific Data
                     {
-                        ToUUID ("5025030f-842f-4ab4-a561-99a5189762d0") /* Unknown UUID */, 
+                        ToUUID ("5025030f-842f-4ab4-a561-99a5189762d0"), 
                         Package (0x01)
                         {
                             Package (0x02)
@@ -6818,7 +6838,7 @@
                         })
                     }
 
-                    If ((Arg0 == ToUUID ("ef87eb82-f951-46da-84ec-14871ac6f84b") /* Unknown UUID */))
+                    If ((Arg0 == ToUUID ("ef87eb82-f951-46da-84ec-14871ac6f84b")))
                     {
                         If ((Arg2 == Zero))
                         {
@@ -7416,10 +7436,10 @@
 
                 If ((Local2 >= 0x07))
                 {
-                    ^^^^PLTF.C00C._PPC () = Local3
-                    ^^^^PLTF.C00D._PPC () = Local3
-                    ^^^^PLTF.C00E._PPC () = Local3
-                    ^^^^PLTF.C00F._PPC () = Local3
+                    ^^^^PLTF.C00C._PPC = Local3
+                    ^^^^PLTF.C00D._PPC = Local3
+                    ^^^^PLTF.C00E._PPC = Local3
+                    ^^^^PLTF.C00F._PPC = Local3
                 }
 
                 Notify (^^^^PLTF.C000, 0x80) // Status Change
```
Note that comment block after the `DefinitionBlock`. It looks like that the decompilation in your system produced some warnings that it didn't produce on mine (that explains the offset during patching) and a different result in some places (probably incomplete). I am not a ACPI expert, so I don't know if this when recompiled would work, or maybe it resulted in broken tables and got ignored by the kernel (can you see any clues in `dmesg`?). 

Now, that may be because your `acpica` is older (2019) than mine (2021) or there is some slight BIOS difference (I noted that the checksum is different, but that might also be due to different `acpica`). Ideally you should maybe try compiling the latest one from https://github.com/acpica/acpica and check if you can get a decompilation without warnings.

**Comment by lbschenkel** [comment]
> well, I managed to get it to work by following the manual approach! I cannot believe I did not try that sooner. (*) based on the fact that my `acpi-override.img` is now different than what was previously under `/boot`, I guess there is some workflow issue in your makefile, rather than in the DSDT patch.

That is strange. My own system is running the result of the Makefile. ~Since you ran manually and it worked, and the Makefile did not work, can you please point out where the Makefile "broke down" for you? Do run `make clean` and then `make` to start from a clean slate.~ Never mind, I found the problem, my Makefile has a small difference compared to the version in Github. Apparently I forgot to push the latest changes. Will fix that right now.  

> as a suggestion, you could try and explicitly print out the necessary commands,

I did. It's in the README under "manual process". I included the exact commands since I would not run a `Makefile` made by a stranger that tries to run `sudo`...

**Comment by piramiday** [comment]
> That is strange. My own system is running the result of the Makefile. Since you ran manually and it worked, and the Makefile did not work, can you please point out where the Makefile "broke down" for you? Do run `make clean` and then `make` to start from a clean slate.

that is just my guess, of course.
I did fully remove the folder and re-cloned this repo before attempting the manual process.
after a successful reboot, though, will the `acpidump` command return already-patched DSDT files?
sorry, but I am still a bit confused by the process.

> I did. It's in the README under "manual process".

they are slightly different than what the makefile is doing, for example with respect to the `-patched` suffix, and the going in and out of folders.
that's not fatal, but it does require a bit of application, also considering the makefile variables (`$@` and `$?`) that I had to revisit.

> I included the exact commands since I would not run a `Makefile` made by a stranger that tries to run `sudo`...

of course, I did read the makefile line by line at first. who wouldn't? :smile:

**Comment by lbschenkel** [comment]
Sorry, the Makefile was indeed buggy. I did not notice until now that I pushed an earlier version with missing parenthesis which resulted in the patched file being overwritten with the original version. That is why it did not have any effect for you.

> after a successful reboot, though, will the `acpidump` command return already-patched DSDT files? sorry, but I am still a bit confused by the process.

Yes, it does. After doing this and rebooting, from the kernel's perspective now the patched ACPI tables are the "real" ones, so if you ask the kernel to dump them you get the patched version, not what's in your firmware. To redo this process from scratch you need to edit the command line in GRUB before booting and remove `initrd=acpi-override.img` so the kernel loads what's in the firmware. 

> 
> > I did. It's in the README under "manual process".
> 
> they are slightly different than what the makefile is doing, for example with respect to the `-patched` suffix, and the going in and out of folders. that's not fatal, but it does require a bit of application, also considering the makefile variables (`$@` and `$?`) that I had to revisit.

Yes, I documented the simplest set of steps possible to avoid distractions. The Makefile is just trying to do it "slightly better" by avoiding cluttering the current directory and separating the patched file from the original one, but if you follow the manual process you should end up having the same result.

> > I included the exact commands since I would not run a `Makefile` made by a stranger that tries to run `sudo`...
> 
> of course, I did read the makefile line by line at first. who wouldn't? smile

---

Could you please "undo" the changes in GRUB and test the fixed Makefile again? I believe that it will just work now. I hope the next person doesn't go through the same frustration that you did.

**Comment by piramiday** [comment]
confirmed working as expected, makefile included. thank you! :rocket: 

also, confirmed working with kernel 5.13. :+1:

**Comment by lbschenkel** [comment]
Great! However, given the warnings that your version of `acpica` is producing on decompile, plus the slight differences on the tables, check if there aren't any kernel warnings and also be watchful for problems. If I were you I would try to upgrade it (or compile it myself if it comes to that) and put that version in `$PATH` before running the makefile. You only need to do this once.

**Comment by piramiday** [comment]
thanks again, I will pay attention to any misbehaviour, and I will upgrade `acpica-tools` if the need arises.
any suggestion with respect to specific system logs to be carefully checked?

**Comment by lbschenkel** [comment]
Nothing specific, but maybe `dmesg | grep -E -i 'acpi|dsdt|bug|warn|error'` and looking for anything strange.
