### ISSUE TITLE
Please add a note on deleting UEFI-Mics-* enteries otherwise one cannot access the UEFI settings again

### ISSUE THREAD

**Issue by rproj1121123** [lbschenkel/acer-sf314_43-acpi-patch#3]
The parent project notes this. When I used this tool to enable S3 sleep (Which btw worked perfectly on my Swift SF314-42 with UEFI version 1.08) I am unable to access the UEFI setup page(by pressing F2 when booting) and it was said to be the result of a bug that adds a whole bunch of UEFI-Misc-* enteries in the F12 Boot Menu. This tool can also be used to delete those. Please also mention this in your readme

**Comment by lbschenkel** [comment]
Included in README.
